package edu.mams.app.forms;

import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.mams.app.model.schedule.Assignment;
import edu.mams.app.model.schedule.Course;
import edu.mams.app.model.schedule.Day;
import edu.mams.app.model.schedule.Week;
import edu.mams.app.model.util.ScheduleBuilder;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.time.LocalDate;
import java.util.*;
import java.util.List;
import java.util.function.BiFunction;

import static edu.mams.app.forms.WeekEdit.fmt;

public class QuickGenerateDialog extends JDialog {
    private JPanel rootPanel;
    private JLabel infoLabel;
    private JScrollPane scrollPane;
    private JPanel listPanel;
    private JButton generateButton;
    private JButton cancelButton;

    private final Map<LocalDate, JComboBox<String>> comboByDate = new LinkedHashMap<>();
    private final Map<LocalDate, List<Assignment>> classesByDate = new LinkedHashMap<>();
    private final Map<LocalDate, JCheckBox> splitByDate = new LinkedHashMap<>();
    private final Map<LocalDate, JComboBox<String>> splitCourseComboByDate = new LinkedHashMap<>();
    private boolean generated = false;

    private final Week week;
    private final List<String> templateNames;
    private final List<Assignment> allClasses;
    private final BiFunction<LocalDate, List<Assignment>, List<Assignment>> pickClassesForDate;

    public QuickGenerateDialog(
            Window owner,
            Week week,
            List<String> templateNames,
            List<Assignment> allClasses,
            BiFunction<LocalDate, List<Assignment>, List<Assignment>> pickClassesForDate
    ) {
        super(owner, "Quick Generate", ModalityType.APPLICATION_MODAL);

        this.week = Objects.requireNonNull(week);
        this.templateNames = Objects.requireNonNull(templateNames);
        this.allClasses = Objects.requireNonNull(allClasses);
        this.pickClassesForDate = Objects.requireNonNull(pickClassesForDate);

        setContentPane(rootPanel);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        infoLabel.setText("Choose a template for each day, then click Generate.");

        // dynamic content area
        listPanel.setLayout(new BoxLayout(listPanel, BoxLayout.Y_AXIS));
        scrollPane.setViewportView(listPanel);

        // init per-day classes
        for (LocalDate d : getWeekDates(week)) {
            Day day = week.getDay(d);
            List<Assignment> initial = (day != null && day.getClasses() != null && !day.getClasses().isEmpty())
                    ? new ArrayList<>(day.getClasses())
                    : new ArrayList<>(allClasses);
            classesByDate.put(d, initial);
        }

        buildRows();

        cancelButton.addActionListener(_ -> dispose());
        generateButton.addActionListener(_ -> {
            generated = true;
            dispose();
        });

        setPreferredSize(new Dimension(520, 640));
        pack();
        setLocationRelativeTo(owner);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(10, 10));
        rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        infoLabel = new JLabel();
        infoLabel.setText("Label");
        rootPanel.add(infoLabel, BorderLayout.NORTH);
        scrollPane = new JScrollPane();
        rootPanel.add(scrollPane, BorderLayout.CENTER);
        listPanel = new JPanel();
        listPanel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        scrollPane.setViewportView(listPanel);
        listPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createRaisedBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        rootPanel.add(panel1, BorderLayout.SOUTH);
        generateButton = new JButton();
        generateButton.setText("Generate");
        panel1.add(generateButton);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        panel1.add(cancelButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void buildRows() {
        listPanel.removeAll();

        for (LocalDate date : getWeekDates(week)) {
            listPanel.add(makeRow(date));
            listPanel.add(Box.createVerticalStrut(6));
        }

        listPanel.revalidate();
        listPanel.repaint();
    }

    private static List<LocalDate> getWeekDates(Week week) {
        List<LocalDate> dates = new ArrayList<>();
        for (Day day : week.getDays()) dates.add(day.getDate());
        dates.sort(Comparator.naturalOrder());
        return dates;
    }

    private JPanel makeRow(LocalDate date) {
        JPanel row = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(0, 0, 0, 8);

        Day day = week.getDay(date);

        // ---- line 0: date label + template combo ----
        JLabel dayLabel = new JLabel(fmt(date));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.WEST;
        row.add(dayLabel, gbc);

        JComboBox<String> combo = new JComboBox<>(templateNames.toArray(new String[0]));
        combo.setEditable(false);
        if (combo.getItemCount() > 0) combo.setSelectedIndex(0);

        // preselect existing template if present
        if (day != null && day.getTemplate() != null) {
            combo.setSelectedItem(day.getTemplate());
        } else {
            switch (date.getDayOfWeek().getValue()) {
                case 1, 5 -> combo.setSelectedItem("Class Meeting Day");
                case 2 -> combo.setSelectedItem("Homeroom Day");
                case 3 -> combo.setSelectedItem("Flex Day");
                case 4 -> combo.setSelectedItem("PE Day");
            }
        }

        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        row.add(combo, gbc);

        // ---- line 1: classes picker ----
        JPanel classesLine = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        classesLine.setOpaque(false);

        JLabel classesLabel = new JLabel();
        List<Assignment> current = classesByDate.get(date);
        int count = current == null ? 0 : current.size();
        classesLabel.setText("Classes: " + count);

        JButton pickClasses = new JButton("Select Classes");
        pickClasses.addActionListener(_ -> {
            List<Assignment> existing = classesByDate.get(date);
            List<Assignment> picked = pickClassesForDate.apply(date, existing);
            classesByDate.put(date, new ArrayList<>(picked));
            classesLabel.setText("Classes: " + picked.size());
        });

        classesLine.add(pickClasses);
        classesLine.add(classesLabel);

        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        row.add(classesLine, gbc);

        // ---- line 2: split checkbox + partner split class selector ----
        JPanel splitLine = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        splitLine.setOpaque(false);

        JCheckBox splitBox = new JCheckBox("Split");
        splitBox.setOpaque(false);

        JComboBox<String> splitCourseCombo = new JComboBox<>();
        splitCourseCombo.setToolTipText("Partner split class");

        // build options
        splitCourseCombo.addItem("(None)");
        Course primarySplit = ScheduleBuilder.getSplitClass();
        for (Assignment a : allClasses) {
            if (a instanceof Course c) {
                if (c.equals(primarySplit)) continue;
                splitCourseCombo.addItem(c.getName());
            }
        }

        // preselect from existing day model
        boolean preSplit = day != null && day.isSplit();
        splitBox.setSelected(preSplit);

        if (day != null && day.getSplitCourse() != null) {
            splitCourseCombo.setSelectedItem(day.getSplitCourse().getName());
        } else {
            splitCourseCombo.setSelectedItem("(None)");
        }

        // enable/disable partner selector based on split flag
        splitCourseCombo.setEnabled(splitBox.isSelected());
        splitBox.addActionListener(_ -> splitCourseCombo.setEnabled(splitBox.isSelected()));

        splitLine.add(splitBox);
        splitLine.add(new JLabel("Partner:"));
        splitLine.add(splitCourseCombo);

        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        row.add(splitLine, gbc);

        // store per-date components
        comboByDate.put(date, combo);
        splitByDate.put(date, splitBox);
        splitCourseComboByDate.put(date, splitCourseCombo);

        return row;
    }

    public Map<LocalDate, List<Assignment>> getClassSelections() {
        Map<LocalDate, List<Assignment>> out = new LinkedHashMap<>();
        for (Map.Entry<LocalDate, List<Assignment>> e : classesByDate.entrySet()) {
            out.put(e.getKey(), e.getValue() == null ? null : new ArrayList<>(e.getValue()));
        }
        return out;
    }

    public Map<LocalDate, String> getSelections() {
        Map<LocalDate, String> out = new LinkedHashMap<>();
        for (Map.Entry<LocalDate, JComboBox<String>> e : comboByDate.entrySet()) {
            Object sel = e.getValue().getSelectedItem();
            out.put(e.getKey(), sel == null ? null : sel.toString());
        }
        return out;
    }

    public Map<LocalDate, String> getSplitCourseSelections() {
        Map<LocalDate, String> out = new LinkedHashMap<>();
        for (Map.Entry<LocalDate, JComboBox<String>> e : splitCourseComboByDate.entrySet()) {
            Object sel = (e.getValue() == null) ? null : e.getValue().getSelectedItem();
            out.put(e.getKey(), sel == null ? null : sel.toString());
        }
        return out;
    }

    public Map<LocalDate, Boolean> getSplitSelections() {
        Map<LocalDate, Boolean> out = new LinkedHashMap<>();
        for (Map.Entry<LocalDate, JCheckBox> e : splitByDate.entrySet()) {
            out.put(e.getKey(), e.getValue() != null && e.getValue().isSelected());
        }
        return out;
    }

    public boolean wasGenerated() {
        return generated;
    }
}
