package edu.mams.app.forms;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.mams.app.model.people.Teacher;
import edu.mams.app.model.requests.AllSchoolRequest;
import edu.mams.app.model.requests.AvoidTimeRequest;
import edu.mams.app.model.requests.TeacherRequest;
import edu.mams.app.model.requests.TeacherTimeRequest;
import edu.mams.app.model.schedule.Assignment;
import edu.mams.app.model.schedule.Course;
import edu.mams.app.model.schedule.Day;
import edu.mams.app.model.schedule.Week;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;
import java.time.Duration;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.List;

/**
 * Request viewer/editor for a Week.
 * <p>
 * Notes:
 * - This code assumes Day#getRequests() returns a non-null List (recommended).
 * - Adjust weekDays(...) to match your Week API.
 */
public final class RequestViewerDialog extends JDialog {
    private final Week week;
    private final List<Teacher> teachers;         // used for pickers
    private final List<Assignment> assignments;   // used for pickers

    private final RequestTableModel tableModel;
    private JTable table;
    private JPanel rootPanel;
    private JScrollPane tableScroll;
    private JPanel btns;
    private JButton closeButton;
    private JButton deleteButton;
    private JButton editButton;
    private JButton addButton;

    public RequestViewerDialog(Window owner, Week week, List<Teacher> teachers, List<Assignment> assignments) {
        super(owner, "Requests", ModalityType.APPLICATION_MODAL);

        this.tableModel = new RequestTableModel(week);

        this.week = Objects.requireNonNull(week, "week");
        this.teachers = teachers != null ? teachers : List.of();
        this.assignments = assignments != null ? assignments : List.of();

        table.setModel(tableModel);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setAutoCreateRowSorter(true);

        editButton.setEnabled(false);
        deleteButton.setEnabled(false);

        table.getSelectionModel().addListSelectionListener(_ -> {
            boolean selected = table.getSelectedRow() >= 0;
            editButton.setEnabled(selected);
            deleteButton.setEnabled(selected);
        });

        addButton.addActionListener(_ -> onAdd());
        editButton.addActionListener(_ -> onEdit());
        deleteButton.addActionListener(_ -> onDelete());
        closeButton.addActionListener(_ -> dispose());

        setContentPane(rootPanel);
        setMinimumSize(new Dimension(900, 420));
        setLocationRelativeTo(owner);
    }


    public RequestViewerDialog(Window owner, Week week) {
        this(owner, week, null, null);
    }

    public RequestViewerDialog(Window owner, Week week, List<Assignment> assignments) {
        this(owner, week, deriveTeachers(assignments), assignments);
    }

    private static List<Teacher> deriveTeachers(List<Assignment> assignments) {
        if (assignments == null) return List.of();

        // avoid duplicates + null teachers
        Set<Teacher> teachers = new LinkedHashSet<>();
        for (Assignment a : assignments) {
            if (a instanceof Course c && c.getTeacher() != null) {
                teachers.add(c.getTeacher());
            }
        }
        return new ArrayList<>(teachers);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tableScroll = new JScrollPane();
        rootPanel.add(tableScroll, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table = new JTable();
        tableScroll.setViewportView(table);
        btns = new JPanel();
        btns.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        rootPanel.add(btns, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        addButton = new JButton();
        addButton.setText("Add");
        btns.add(addButton);
        editButton = new JButton();
        editButton.setText("Edit");
        btns.add(editButton);
        deleteButton = new JButton();
        deleteButton.setText("Delete");
        btns.add(deleteButton);
        closeButton = new JButton();
        closeButton.setText("Close");
        btns.add(closeButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    private void onAdd() {
        RequestEditDialog dlg = new RequestEditDialog(
                this,
                weekDays(week),
                teachers,
                assignments,
                null,
                null
        );
        dlg.setVisible(true);
        if (dlg.notSaved()) return;

        Day targetDay = dlg.getSelectedDay();
        TeacherRequest newReq = dlg.buildRequest();

        requireRequestsList(targetDay).add(newReq);
        tableModel.reload();
    }

    private void onEdit() {
        RequestRow rr = getSelectedRowOrNull();
        if (rr == null) return;

        RequestEditDialog dlg = new RequestEditDialog(
                this,
                weekDays(week),
                teachers,
                assignments,
                rr.day,
                rr.request
        );
        dlg.setVisible(true);
        if (dlg.notSaved()) return;

        Day newDay = dlg.getSelectedDay();
        TeacherRequest replacement = dlg.buildRequest();

        if (rr.day != newDay) {
            requireRequestsList(rr.day).remove(rr.request);
            requireRequestsList(newDay).add(replacement);
        } else {
            List<TeacherRequest> list = requireRequestsList(rr.day);
            int idx = list.indexOf(rr.request);
            if (idx >= 0) list.set(idx, replacement);
            else list.add(replacement);
        }

        tableModel.reload();
    }

    private void onDelete() {
        RequestRow rr = getSelectedRowOrNull();
        if (rr == null) return;

        int ok = JOptionPane.showConfirmDialog(
                this,
                "Delete this request?\n\n" + tableModel.describe(rr),
                "Confirm Delete",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (ok != JOptionPane.OK_OPTION) return;

        requireRequestsList(rr.day).remove(rr.request);
        tableModel.reload();
    }

    private RequestRow getSelectedRowOrNull() {
        int viewRow = table.getSelectedRow();
        if (viewRow < 0) return null;

        int modelRow = table.convertRowIndexToModel(viewRow);
        return tableModel.getRow(modelRow);
    }

    private static List<TeacherRequest> requireRequestsList(Day day) {
        List<TeacherRequest> reqs = day.getRequests();
        if (reqs == null) {
            throw new IllegalStateException(
                    "Day.getRequests() returned null. Initialize the list in Day (recommended)."
            );
        }
        return reqs;
    }

    // ---------------- Week/day helpers ----------------

    private static List<Day> weekDays(Week week) {
        // Adjust depending on your Week API.
        // Preferred: Week#getDays() returns a non-null List<Day>.
        List<Day> days = week.getDays();
        if (days != null) return days;

        // If you *actually* have week.getDay(i), replace this block accordingly.
        return List.of();
    }

    // ---------------- Table model ----------------

    private static final class RequestRow {
        final Day day;
        final TeacherRequest request;

        RequestRow(Day day, TeacherRequest request) {
            this.day = day;
            this.request = request;
        }
    }

    private static final class RequestTableModel extends AbstractTableModel {

        private static final String[] COLS = {
                "Day",
                "Type",
                "Teacher",
                "Assignment",
                "Reason",
                "Start",
                "Length"
        };

        private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("H:mm");

        private final Week week;
        private final List<RequestRow> rows = new ArrayList<>();

        RequestTableModel(Week week) {
            this.week = Objects.requireNonNull(week, "week");
            reload();
        }

        void reload() {
            rows.clear();

            for (Day d : weekDays(week)) {
                if (d == null) continue;
                List<TeacherRequest> reqs = d.getRequests();
                if (reqs == null) continue;

                for (TeacherRequest r : reqs) {
                    if (r != null) rows.add(new RequestRow(d, r));
                }
            }

            fireTableDataChanged();
        }

        RequestRow getRow(int row) {
            return rows.get(row);
        }

        String describe(RequestRow rr) {
            return rr.request.getClass().getSimpleName() + ": " + rr.request;
        }

        @Override
        public int getRowCount() {
            return rows.size();
        }

        @Override
        public int getColumnCount() {
            return COLS.length;
        }

        @Override
        public String getColumnName(int column) {
            return COLS[column];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            RequestRow rr = rows.get(rowIndex);
            Day d = rr.day;
            TeacherRequest r = rr.request;

            String dayLabel = safeDayLabel(d);
            String type = r.getClass().getSimpleName();
            String teacher = r.getTeacher() != null ? r.getTeacher().toString() : "";
            String assignment = r.getAssignment() != null ? r.getAssignment().toString() : "";
            String reason = r.getReason() != null ? r.getReason() : "";

            String start = "";
            String length = "";
            if (r instanceof TeacherTimeRequest ttr) {
                if (ttr.getStartTime() != null) start = TIME_FMT.format(ttr.getStartTime());
                if (ttr.getLength() != null) length = prettyDuration(ttr.getLength());
            }

            return switch (columnIndex) {
                case 0 -> dayLabel;
                case 1 -> type;
                case 2 -> teacher;
                case 3 -> assignment;
                case 4 -> reason;
                case 5 -> start;
                case 6 -> length;
                default -> "";
            };
        }

        private static String safeDayLabel(Day d) {
            // Adjust to your Day API (date/dayNumber/etc.)
            try {
                if (d.getDate() != null) return d.getDate().toString();
            } catch (Exception ignored) {
            }
            try {
                return "Day " + d.getDayNumber();
            } catch (Exception ignored) {
            }
            return String.valueOf(d);
        }

        private static String prettyDuration(Duration dur) {
            long mins = dur.toMinutes();
            if (mins % 60 == 0) return (mins / 60) + " hr";
            if (mins > 60) return (mins / 60) + " hr " + (mins % 60) + " min";
            return mins + " min";
        }
    }

    // ---------------- Editor dialog ----------------

    private static final class RequestEditDialog extends JDialog {

        private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("H:mm");

        private boolean saved = false;

        private final JComboBox<Day> dayBox;
        private final JComboBox<RequestType> typeBox;

        private final JComboBox<Teacher> teacherBox;
        private final JComboBox<Assignment> assignmentBox;

        private final JTextField reasonField = new JTextField();
        private final JTextField startTimeField = new JTextField("8:00");
        private final JTextField lengthMinField = new JTextField("30");

        private enum RequestType {
            AVOID_TIME("AvoidTimeRequest"),
            ALL_SCHOOL("AllSchoolRequest");

            final String label;

            RequestType(String label) {
                this.label = label;
            }

            @Override
            public String toString() {
                return label;
            }

            static RequestType from(TeacherRequest r) {
                if (r instanceof AllSchoolRequest) return ALL_SCHOOL;
                return AVOID_TIME;
            }
        }

        RequestEditDialog(
                Window owner,
                List<Day> days,
                List<Teacher> teachers,
                List<Assignment> assignments,
                Day initialDay,
                TeacherRequest initialRequest
        ) {
            super(owner, initialRequest == null ? "Add Request" : "Edit Request", ModalityType.APPLICATION_MODAL);

            dayBox = new JComboBox<>(days.toArray(new Day[0]));
            typeBox = new JComboBox<>(RequestType.values());

            teacherBox = new JComboBox<>(teachers.toArray(new Teacher[0]));
            assignmentBox = new JComboBox<>(assignments.toArray(new Assignment[0]));

            dayBox.setRenderer(new DefaultListCellRenderer() {
                @Override
                public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    if (value instanceof Day d) setText(RequestTableModel.safeDayLabel(d));
                    return this;
                }
            });

            initFromExisting(initialDay, initialRequest);
            setContentPane(buildRootPanel());

            setMinimumSize(new Dimension(520, 520));
            setLocationRelativeTo(owner);
        }

        private void initFromExisting(Day initialDay, TeacherRequest initialRequest) {
            if (initialDay != null) dayBox.setSelectedItem(initialDay);
            if (initialRequest == null) return;

            typeBox.setSelectedItem(RequestType.from(initialRequest));

            if (initialRequest.getTeacher() != null) teacherBox.setSelectedItem(initialRequest.getTeacher());
            if (initialRequest.getAssignment() != null) assignmentBox.setSelectedItem(initialRequest.getAssignment());
            if (initialRequest.getReason() != null) reasonField.setText(initialRequest.getReason());

            if (initialRequest instanceof TeacherTimeRequest ttr) {
                if (ttr.getStartTime() != null) startTimeField.setText(TIME_FMT.format(ttr.getStartTime()));
                if (ttr.getLength() != null) lengthMinField.setText(Long.toString(ttr.getLength().toMinutes()));
            }
        }

        private JPanel buildRootPanel() {
            JPanel root = new JPanel(new BorderLayout(10, 10));
            root.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

            root.add(buildFormPanel(), BorderLayout.CENTER);
            root.add(buildButtonBar(), BorderLayout.SOUTH);

            return root;
        }

        private JPanel buildFormPanel() {
            JPanel form = new JPanel(new GridBagLayout());
            GridBagConstraints c = new GridBagConstraints();
            c.insets = new Insets(6, 6, 6, 6);
            c.fill = GridBagConstraints.HORIZONTAL;

            int y = 0;

            addRow(form, c, y++, "Day:", dayBox);
            addRow(form, c, y++, "Type:", typeBox);
            addRow(form, c, y++, "Teacher:", teacherBox);
            addRow(form, c, y++, "Assignment:", assignmentBox);
            addRow(form, c, y++, "Reason:", reasonField);
            addRow(form, c, y++, "Start time (H:mm):", startTimeField);
            addRow(form, c, y, "Length (minutes):", lengthMinField);

            return form;
        }

        private JPanel buildButtonBar() {
            JButton saveBtn = new JButton("Save");
            JButton cancelBtn = new JButton("Cancel");

            saveBtn.addActionListener(_ -> {
                try {
                    validateInputs();
                    saved = true;
                    dispose();
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Invalid Input", JOptionPane.ERROR_MESSAGE);
                }
            });

            cancelBtn.addActionListener(_ -> dispose());

            JPanel btns = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            btns.add(saveBtn);
            btns.add(cancelBtn);

            return btns;
        }

        private static void addRow(JPanel form, GridBagConstraints c, int row, String label, JComponent field) {
            c.gridx = 0;
            c.gridy = row;
            c.weightx = 0;
            form.add(new JLabel(label), c);

            c.gridx = 1;
            c.gridy = row;
            c.weightx = 1;
            form.add(field, c);
        }

        private void validateInputs() {
            if (dayBox.getSelectedItem() == null) throw new IllegalArgumentException("Pick a day.");
            if (typeBox.getSelectedItem() == null) throw new IllegalArgumentException("Pick a request type.");
            if (teacherBox.getSelectedItem() == null) throw new IllegalArgumentException("Pick a teacher.");

            // start time parse
            parseTime(startTimeField.getText());

            // length parse
            long mins = parseMinutes(lengthMinField.getText());
            if (mins <= 0) throw new IllegalArgumentException("Length must be a positive number of minutes.");
        }

        private static LocalTime parseTime(String s) {
            try {
                return LocalTime.parse(s.trim(), TIME_FMT);
            } catch (DateTimeParseException ex) {
                throw new IllegalArgumentException("Start time must be like 8:00 or 13:30 (H:mm).");
            }
        }

        private static long parseMinutes(String s) {
            try {
                return Long.parseLong(s.trim());
            } catch (NumberFormatException ex) {
                throw new IllegalArgumentException("Length must be an integer number of minutes.");
            }
        }

        boolean notSaved() {
            return !saved;
        }

        Day getSelectedDay() {
            return (Day) dayBox.getSelectedItem();
        }

        TeacherRequest buildRequest() {
            Teacher teacher = (Teacher) teacherBox.getSelectedItem();
            Assignment assignment = (Assignment) assignmentBox.getSelectedItem();
            String reason = reasonField.getText() != null ? reasonField.getText().trim() : "";

            LocalTime start = parseTime(startTimeField.getText());
            Duration len = Duration.ofMinutes(parseMinutes(lengthMinField.getText()));

            RequestType type = (RequestType) typeBox.getSelectedItem();
            if (type == null) throw new IllegalStateException("Request type not selected.");

            return switch (type) {
                case ALL_SCHOOL -> buildAllSchool(teacher, assignment, reason, start, len);
                case AVOID_TIME -> buildAvoidTime(teacher, assignment, reason, start, len);
            };
        }

        private static AllSchoolRequest buildAllSchool(Teacher teacher, Assignment assignment, String reason, LocalTime start, Duration len) {
            AllSchoolRequest r = new AllSchoolRequest();
            r.setTeacher(teacher);
            r.setAssignment(assignment);
            r.setReason(reason);
            r.setStartTime(start);
            r.setLength(len);
            return r;
        }

        private static AvoidTimeRequest buildAvoidTime(Teacher teacher, Assignment assignment, String reason, LocalTime start, Duration len) {
            AvoidTimeRequest r = new AvoidTimeRequest();
            r.setTeacher(teacher);
            r.setAssignment(assignment);
            r.setReason(reason);
            r.setStartTime(start);
            r.setLength(len);
            return r;
        }
    }
}
