package edu.mams.app.forms;

import edu.mams.app.model.schedule.Schedule;
import edu.mams.app.model.schedule.Week;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class WeekSelector extends JFrame {
    private static final File FILE = new File("schedule.json");
    private static final DateTimeFormatter DISPLAY_FMT = DateTimeFormatter.ofPattern("EEE, MMM d, yyyy");
    private final Schedule schedule;
    private JButton cancelButton;
    private JPanel contentPane;
    private JButton newWeekButton;
    private JButton openButton;
    private JList<LocalDate> weekList;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public WeekSelector(Schedule schedule) {
        this.schedule = schedule;

        // GUI setup
        setContentPane(contentPane);
        setTitle("Week Selector");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(500, 650);
        setLocationRelativeTo(null);

        initWeekList();
        initActions();
    }

    // ===== Initialize list =====
    private void initWeekList() {
        DefaultListModel<LocalDate> model = new DefaultListModel<>();

        schedule.getWeekStartDates().stream().sorted().forEach(model::addElement);

        weekList.setModel(model);
        weekList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        weekList.setFixedCellHeight(34);

        weekList.setCellRenderer((list, value, index, isSelected, cellHasFocus) -> {
            JLabel lbl = new JLabel(value.format(DISPLAY_FMT));
            lbl.setOpaque(true);
            lbl.setBorder(BorderFactory.createEmptyBorder(6, 12, 6, 12));
            lbl.setBackground(isSelected ? list.getSelectionBackground() : list.getBackground());
            lbl.setForeground(isSelected ? list.getSelectionForeground() : list.getForeground());
            return lbl;
        });

        if (!model.isEmpty()) {
            weekList.setSelectedIndex(0);
        }
    }

    // ===== Button actions =====
    private void initActions() {

        openButton.addActionListener(e -> openSelectedWeek());

        newWeekButton.addActionListener(e -> {
            LocalDate newStart = schedule.getWeekStartDates().stream().max(LocalDate::compareTo).orElse(LocalDate.of(2025, 12, 1).minusWeeks(1)).plusWeeks(1);

            Week newWeek = new Week(newStart);
            schedule.addWeek(newWeek);
            schedule.saveToFile(FILE);

            refreshList();
            weekList.setSelectedValue(newStart, true);
        });

        cancelButton.addActionListener(e -> dispose());

        // Double-click to open
        weekList.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    openSelectedWeek();
                }
            }
        });
    }

    private void openSelectedWeek() {
        LocalDate start = weekList.getSelectedValue();
        if (start == null) {
            JOptionPane.showMessageDialog(this, "Select a week first.");
            return;
        }

        Week week = schedule.getWeek(start);
        new WeekEdit(week, schedule).setVisible(true);
        dispose();
    }

    // ===== Helpers =====
    private void refreshList() {
        DefaultListModel<LocalDate> model = (DefaultListModel<LocalDate>) weekList.getModel();

        model.clear();
        schedule.getWeekStartDates().stream().sorted().forEach(model::addElement);
    }

    public static void main(String[] args) {
        Schedule schedule = Schedule.loadFromFile(FILE);
        SwingUtilities.invokeLater(() -> new WeekSelector(schedule).setVisible(true));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        weekList = new JList();
        contentPane.add(weekList, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        contentPane.add(cancelButton, new com.intellij.uiDesigner.core.GridConstraints(1, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        newWeekButton = new JButton();
        newWeekButton.setText("New");
        contentPane.add(newWeekButton, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        openButton = new JButton();
        openButton.setText("Open");
        contentPane.add(openButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }
}
